### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by itsmealwin** [haya14busa/incsearch-fuzzy.vim#2]
First of all, thank you very much for making this plugin.
I have been looking for something like this for a long time..

However, I do have a small request:
Is it possible to fuzzy search only for 1 word? Let me elaborate, I work on Java a lot and as per Java convention, method names and variable names (aside from constants) are camelCase instead of snake_case. Thus I wish that when I type in `/mtdf`, the plugin would search for `methodFoo` instead of `method Foo` or `method_Foo` (which is currently the case).

I hope my question is clear enough. Thank you in advance for your answer and happy new year!

**Comment by haya14busa** [comment]
Thank you for the suggestion, it's interesting!
Can you try this branch with below mappings?  https://github.com/haya14busa/incsearch-fuzzy.vim/tree/fuzzy-word

``` vim
map z/ <Plug>(incsearch-fuzzyword-/)
map z? <Plug>(incsearch-fuzzyword-?)
map zg/ <Plug>(incsearch-fuzzyword-stay)
```

**Comment by itsmealwin** [comment]
Hello,

Thank you for the fast reply. I tried it and it works perfectly! Just exactly as I wish it to be!
Would you merge this feature into the master?

Thank you again for the awesome plugin!

EDIT: I guess I am closing this issue since you have solved it :+1:

**Comment by haya14busa** [comment]
Thanks. I merged it into master now :sparkles:
